FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential libssl-dev zlib1g-dev yasm pkg-config libgmp-dev libpcap-dev libbz2-dev

COPY . /repo
WORKDIR /repo/src
RUN ./configure
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /repo/run/uaf2john /uaf2john
